# Generated by Django 6.0.5 on 2026-05-25 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("month", models.CharField(max_length=20)),
                ("internal_attendance", models.IntegerField()),
                ("external_attendance", models.IntegerField()),
                ("deaths", models.IntegerField()),
                ("euthanasia", models.IntegerField()),
                ("rescue_requests", models.IntegerField()),
            ],
        ),
    ]
