# Generated by Django 6.0.5 on 2026-05-26 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="report",
            name="rescue_requests",
        ),
        migrations.AddField(
            model_name="report",
            name="animal_donations",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="report",
            name="external_castration",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="report",
            name="internal_castration",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="report",
            name="releases",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="report",
            name="rescue_animals",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="report",
            name="samuvet_requests",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="report",
            name="sheltered_animals",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="report",
            name="deaths",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="report",
            name="euthanasia",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="report",
            name="external_attendance",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="report",
            name="internal_attendance",
            field=models.IntegerField(default=0),
        ),
    ]
