# Generated by Django 6.0.5 on 2026-05-26 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0002_remove_report_rescue_requests_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="animal_donations",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="report",
            name="deaths",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="report",
            name="euthanasia",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="report",
            name="external_attendance",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="report",
            name="external_castration",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="report",
            name="internal_attendance",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="report",
            name="internal_castration",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="report",
            name="releases",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="report",
            name="rescue_animals",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="report",
            name="samuvet_requests",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="report",
            name="sheltered_animals",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
