# Generated by Django 6.0.5 on 2026-05-29 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0003_alter_report_animal_donations_alter_report_deaths_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="donations",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
