# Generated by Django 6.0.5 on 2026-06-08 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0004_report_donations"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="report",
            constraint=models.UniqueConstraint(
                fields=("year", "month"), name="unique_year_month"
            ),
        ),
    ]
